### ISSUE TITLE
Decide on plugin name

### ISSUE THREAD

**Issue by 3ark91** [safatshahin/moodle-qbank_qtoactivity#1]
So any thoughts on names so far? How about 'Cedric'?

**Comment by hacampbell** [comment]
Quactions? As in Qu(iz) Actions

**Comment by LukePM1994** [comment]
I like your line of thinking Henry. What about something like manaquestion/manaquiz (manage question/quiz)

**Comment by Jhojji** [comment]
I was thinking QBankQue, or QBQ for short. I thought that was clever :)

**Comment by 3ark91** [comment]
Good ideas. I was thinking about the functionality of the plugin mostly being the addition of questions from the Question Bank to Activities. Question -> Activity. So thinking ideas along the lines of Question2Activity or similar abbreviation Q2A, Q2Act etc. Or alternatively something like Question Router, Question Shifter, QuestionBank Push. Again potentially abbreviating to something a bit quicker to say.

**Comment by Jhojji** [comment]
My suggestion was QbankQue because we would be "Queuing" questions to add to an activity, and it immediately alerts a user that the plugin works through question bank. It might be a bit too on the nose though, or maybe not descriptive enough?

 Of your suggestions Mark, I like QBankPush the most. 

I like Quactions, its catchy and neat, but personally I feel we're not adding enough functionality to the quiz activity or questions to name ourselves question actions, if that makes sense? Seems too strong of a standalone name for something we're developing to work heavily off another plugin.

 Manaquiz is catchy enough, but maybe a bit misleading? ManaQuestions is less so, but a bit more clunky I feel. Might be the sort of thing potential users would search for a plugin like ours, however.

**Comment by 3ark91** [comment]
Yeah I think QBank in the name is a good idea like you say Harrison - indicating its utilising qbank, I do think it would have to be 'QbankQueue' though. Anything that quickly indicates the functionality of the plugin to the user perusing the plugins catalogue.

**Comment by hacampbell** [comment]
Jumping off the idea of having Qbank in the name and it describing the action, what about "Qbank Enqueue" which can be shortened to "Q-Enqueue" or "QenQ"

**Comment by LukePM1994** [comment]
Of the names suggested, I thought I'd take Safat's advice and name my top 4.

QBankQueue - QBQ
Q-Enqueue - QenQ
Question2Activity - Q2Act
QBank Push

Let me know if your list differs!

**Comment by 3ark91** [comment]
Those 4 all seem good to me Luke - If the others are happy we should have a vote from those 4. If Safat is happy to vote as well we will avoid ties and definitely have a selection made.

**Comment by hacampbell** [comment]
Yep, those are my top 4 as well. Happy to move on to the vote and get this one tied up.

**Comment by hacampbell** [comment]
After a vote, the name Question2Activity (qbank_q2activity) has been chosen.
